### ISSUE TITLE
Compile error on QSE

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.bytes#18]
I tried to compile on the 4.2. QSE and I get this error:
```

In file included from /home/streamsadmin/Downloads/streamsx.hbase.bluemix_0.1/toolkits/com.ibm.streamsx.bytes/impl/include/BytesFunctions.h:9,
                 from src/function/com/ibm/streamsx/hbase/bluemix/hbaseGet.cpp:4:
/home/streamsadmin/Downloads/streamsx.hbase.bluemix_0.1/toolkits/com.ibm.streamsx.bytes/impl/include/util.h:9:28: error: boost/assign.hpp: No such file or directory
In file included from /home/streamsadmin/Downloads/streamsx.hbase.bluemix_0.1/toolkits/com.ibm.streamsx.bytes/impl/include/BytesFunctions.h:9,
                 from src/function/com/ibm/streamsx/hbase/bluemix/hbaseGet.cpp:4:
/home/streamsadmin/Downloads/streamsx.hbase.bluemix_0.1/toolkits/com.ibm.streamsx.bytes/impl/include/util.h:14: error: ‘boost’ has not been declared
make: *** [build/function/com/ibm/streamsx/hbase/bluemix/hbaseGet.o] Error 1
CDISP0141E ERROR: The compilation of the generated code failed.
```

**Comment by natashadsilva** [comment]
I think the BytesFunctions.h also uses the boost library instead of streams_Boost and needs to be changed as well.
